# @file SBCL-test.yml
---
name: SBCL-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Install Glibc
        run: sudo apt install glibc

      - name: Download sbcl
        run: |
          curl -o sbcl.tar.bz2 https://pilotfiber.dl.sourceforge.net/project/sbcl/sbcl/2.1.0/sbcl-2.1.0-x86-64-linux-binary.tar.bz2                              
          bzip2 -cd sbcl.tar.bz2 | tar xvf -                                                                                                                     

      - name: Download quicklisp
        run: curl -o quicklisp.lisp 'https://beta.quicklisp.org/quicklisp.lisp'

      - name: Install quicklisp
        run: |
          ./sbcl-2.1.0-x86-64-linux/run-sbcl.sh --noinform --non-interactive --load quicklisp.lisp --eval "(quicklisp-quickstart:install :path \"$GITHUB_WORKSPACE/quicklisp/\")"
          ./sbcl-2.1.0-x86-64-linux/run-sbcl.sh --noinform --non-interactive --load "$GITHUB_WORKSPACE/quicklisp/setup.lisp" --eval '(ql-util:without-prompting (ql:add-to-init-file))'

      - name: Download repo
        uses: actions/checkout@v2
        with:
          path: quicklisp/local-projects/ace.core

      - name: Load and run tests
        run: |
          export PATH="$PATH:$GITHUB_WORKSPACE/quicklisp/local-projects/cl-protobufs/protoc/"
          ./sbcl-2.1.0-x86-64-linux/run-sbcl.sh --noinform --non-interactive  --eval '(ql:quickload :bordeaux-threads)' --eval '(ql:quickload :closer-mop)' --eval '(ql:quickload :ace.core)' 2>&1 | tee  report
          cat report
          ! grep -q "ERROR" report
